apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      tier: frontend
  template:
    metadata:
      labels:
        app: app2
        tier: frontend
    spec:
      containers:
        - name: app2
          image: srlaf/app2:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
    tier: frontend
spec:
  selector:
    app: app2
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:946156973594:certificate/e04a0e90-b64e-4169-bac8-0f73e823cc1c    
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=devops
    alb.ingress.kubernetes.io/group.name: expense
spec:
  ingressClassName: alb
  rules:
    - host: "app2.buddymarket.shop"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: app2
              port:
                number: 80